spring.application.name=jobsync-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jobsync
spring.datasource.username=postgres
spring.datasource.password=Akshi@2325

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Groq API
groq.api.key=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

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
